wip

diff --git a/src/docker-linter-decorator/docker-linter-decorator.yml b/src/docker-linter-decorator/docker-linter-decorator.yml
--- a/src/docker-linter-decorator/docker-linter-decorator.yml
+++ b/src/docker-linter-decorator/docker-linter-decorator.yml
@@ -11,15 +11,23 @@ steps:
               echo "No Dockerfile was found"
         else
               echo "Dockerfile(s) found: $filePath"
-              echo -n -e "\e[0;32mOK\e[0m";
 
               echo 'installing dockerfilelint'
               npm install -g dockerfilelint --silent
               echo 'Installed version: '
               dockerfilelint -v
-              echo -n -e "\e[0;32mOK\e[0m";
 
               echo 'running dockerfilelint'
-              find -type f -name 'Dockerfile' -exec dockerfilelint {} \;
+              result=$(find -type f -name 'Dockerfile' -exec dockerfilelint {} \;)
               # explanation of find+exec: https://stackoverflow.com/questions/9612090/how-to-loop-through-file-names-returned-by-find
+
+              # dockerfilelint does not have proper exit code
+              echo $result
+
+              if echo "$result" | grep -q "None found"; then
+                  echo "no issues found"
+              else
+                  echo "issues found"
+                  exit 1
+              fi
         fi
